### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by bmangus** [Luidog/fms-api-client#42]
Disclaimer, this may not be a bug. Here is the issue I am experiencing just in case it's not just me.

**Describe the bug**
Every other request through client.create() method times out. Request 1,3,5,7,9... all fine. Request 2,4,6,8... timeout.

**Expected behavior**
100% success or failure.

**Code Examples**
(apologies for the excessive console.log, comes in handy below)
```
const { Filemaker } = require('fms-api-client');
const { connect } = require('marpat');

const fmUrl = process.env.FM_URL;
const fmApiPath = process.env.FM_APIPATH;
const fmDbname = process.env.FM_DBNAME;
const fmLayout = process.env.FM_LAYOUT;
const fmUsername = process.env.FM_USER;
const fmPassword = process.env.FM_PW;


const execute = (body, cb, client) => {
  connect('nedb://memory')
    .then(db => {
      if(typeof client !== 'undefined'){
        console.log(client);
      }else{
        console.log("Client not defined entering filemaker.js");
      }
      client = Filemaker.create({
        application: fmDbname,
        server: fmUrl,
        user: fmUsername,
        password: fmPassword,
        agent: {rejectUnauthorized: false}
      });
      console.log("Initial client - line 28");
      return client.save()
      .then(client => {
        console.log("Post Initial Save - line 31")
        client.create(fmLayout, {
         FormBody: body
        })
        .then(client => {
          console.log('Post Record Create - line 36');
          cb(null, client);
        })
        .catch(err => {
          console.log("Error on record creation - line 40");
          cb(err, null);
        });
      })
      .catch(err => {
        console.log("Error on intial client save - line 45");
        cb(err, null);
      });
    })
    .catch(err => {
      console.log("Larger Error otherwise unspecified....");
      console.log(err);
    });


}


module.exports = {
  execute: (body, cb) => {
    execute(body, (err, result) => {
        cb(err, result)
    })
  }
}
```

**Tests**
N/A

**Additional context**
Here is a sample of the console output running on my local machine over the course of three requests: 

```
listening on port 3000.....
##### REQUEST 1 ############
express deprecated res.send(status): Use res.sendStatus(status) instead app.js:22:7
Client not defined entering filemaker.js
Initial client - line 28
Post Initial Save - line 31
Post Record Create - line 36
null (success)
##### REQUEST 2 ############
Client not defined entering filemaker.js
Initial client - line 28
Post Initial Save - line 31
Error on record creation - line 40
{ Error: connect ETIMEDOUT 10.10.10.10
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '10.10.10.10',
  port: 443,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        authorization:
         'Basic xxxxxxxxxxxxx',
        'User-Agent': 'axios/0.18.0',
        'Content-Length': 2 },
     method: 'post',
     url:
      'https://someserversomewhere//fmi/data/v1/databases/Tabernacles-2019/sessions',
     data: '{}',
     httpsAgent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     maxRedirects: 0,
     [Symbol(COOKIEJAR_SUPPORT_LOCAL)]:
      { backupOptions: [Object], jar: undefined, redirectCount: 5 } },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] { response: [Function], error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 2,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: false,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        alpnProtocol: null,
        authorized: false,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: 'someserversomewhere',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: [Array],
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 115,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: false,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        alpnProtocol: null,
        authorized: false,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: 'someserversomewhere',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: [Array],
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 115,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _header:
      'POST //fmi/data/v1/databases/Tabernacles-2019/sessions HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nauthorization: Basic xxxxxxxxx\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 2\r\nHost: someserversomewhere\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '//fmi/data/v1/databases/Tabernacles-2019/sessions',
     _ended: false,
     res: null,
     aborted: false,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'content-type': [Array],
        authorization: [Array],
        'user-agent': [Array],
        'content-length': [Array],
        host: [Array] } },
  response: undefined }
(node:38817) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at fmdb.execute (/Users/brianmangus/Desktop/lion-lamb/LL-App/app.js:33:33)
    at execute (/Users/brianmangus/Desktop/lion-lamb/LL-App/filemaker.js:60:9)
    at client.create.then.catch.err (/Users/brianmangus/Desktop/lion-lamb/LL-App/filemaker.js:40:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:38817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:38817) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
#### REQUEST 3 ##########
Client not defined entering filemaker.js
Initial client - line 28
Post Initial Save - line 31
Post Record Create - line 36
null (success)

```

**Comment by Luidog** [comment]
@bmangus I am not sure this is a bug either. Can you tell me the environment you are running this in?

Based on the console log and sample code you gave me the error is occurring on line 40 of filemaker.js. It looks like that is the callback and not an error in fms-api-client. I am assuming the reason for the error is a timeout. I would recommend you look at your environmental configuration. 

Can you run a few test calls from the client to the server and then use the average response time to set the agent timeout property of fms-api-client? Please post here after you have tested with an agent timeout property set.  I am going to close this ticket as the timeout property is working in the automated tests.

 I appreciate you taking the time to bring this to my attention. If we can find a bug I would be glad to fix it.

**Comment by bmangus** [comment]
Sure, it is ultimately going to be running on now v1 using node.js and express for routing. For these tests I am running local on my Mac, using node V11.6.0. I should have included the route file originally, I apologize. You were correct about the callback error, I was trying to convert the result paramter from the callback into a string using JSON.stringify, when it wasn't actually json (duh). That took care of the typerror warning. However, the original intermittent timeout issue holds. I do want to rule out a network issue with my client's FMS17 machine before we proceed down a bug route. I will let you know if I find that we need to continue looking into a bug. I appreciate your time and assistance.

**Comment by bmangus** [comment]
It is definitely a network issue. I implemented a simple retry method, and all records now (eventually) post as expected. Thanks again for your assistance.

**Comment by rahul4694** [comment]
I am getting an { code: 'ECONNABORTED', message: 'timeout of 3000ms exceeded' } error while calling client.login() method
in fms-api-client any help would be appreciable.

**Comment by c0desta** [comment]
> I am getting an { code: 'ECONNABORTED', message: 'timeout of 3000ms exceeded' } error while calling client.login() method
> in fms-api-client any help would be appreciable.

I might have found the bug the connection model has a hardcoded 3000 in it which forces the post request to close in 3000ms

https://github.com/Luidog/fms-api-client/blob/master/src/models/connection.model.js#L187

I updated it to  higher timeout and I don't see any issues now 

It should take the timeout we pass when we init the client create method

@Luidog can you check if the above should be the case and i might be able to make a PR with the fix.

**Comment by Luidog** [comment]
Hey Codesta,

You are right and I would be open to a PR. I added that timeout to ensure that initial authentication didn’t block the event loop for additional requests.

If you create a PR that populates the timeout from  the login method to session creation I’d be happy to test it.

Thank You,

Lui de la Parra
